
> testingtool-app@1.0.0 start /home/perfeasy/testingtool
> nodemon src/ --exec babel-node

[33m[nodemon] 1.18.9[39m
[33m[nodemon] to restart at any time, enter `rs`[39m
[33m[nodemon] watching: *.*[39m
[32m[nodemon] starting `babel-node src/`[39m
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: EBADF: bad file descriptor, read
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testingtool-app@1.0.0 start: `nodemon src/ --exec babel-node`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the testingtool-app@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/perfeasy/.npm/_logs/2019-01-09T08_16_58_177Z-debug.log
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/perfeasy/testingtool/.env'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (/home/perfeasy/testingtool/src/utility/env.js:5:30)
    at Module._compile (module.js:653:30)
    at loader (/home/perfeasy/testingtool/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/perfeasy/testingtool/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/perfeasy/testingtool/src/config/app.js:1:1)
    at Module._compile (module.js:653:30)
    at loader (/home/perfeasy/testingtool/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/perfeasy/testingtool/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:566:32)

> testingtool-app@1.0.0 start /home/perfeasy/testingtool
> nodemon src/ --exec babel-node

[33m[nodemon] 1.18.9[39m
[33m[nodemon] to restart at any time, enter `rs`[39m
[33m[nodemon] watching: *.*[39m
[32m[nodemon] starting `babel-node src/`[39m
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: EBADF: bad file descriptor, read
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testingtool-app@1.0.0 start: `nodemon src/ --exec babel-node`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the testingtool-app@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/perfeasy/.npm/_logs/2019-01-09T08_25_23_632Z-debug.log
ðŸ–¥  Server started at http://0.0.0.0:4000/
(node:31962) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 job ttl exceeded listeners added. Use emitter.setMaxListeners() to increase limit
(node:31962) UnhandledPromiseRejectionWarning: Error: session store is unavailable
    at Timeout.setTimeout (/home/perfeasy/testingtool/node_modules/koa-generic-session/lib/session.js:441:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:31962) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31962) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

> testingtool-app@1.0.0 start /home/perfeasy/testingtool
> nodemon src/ --exec babel-node

[33m[nodemon] 1.18.9[39m
[33m[nodemon] to restart at any time, enter `rs`[39m
[33m[nodemon] watching: *.*[39m
[32m[nodemon] starting `babel-node src/`[39m
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: EBADF: bad file descriptor, read
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testingtool-app@1.0.0 start: `nodemon src/ --exec babel-node`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the testingtool-app@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/perfeasy/.npm/_logs/2019-01-09T08_29_47_167Z-debug.log
ðŸ–¥  Server started at http://0.0.0.0:4000/
(node:32141) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 job ttl exceeded listeners added. Use emitter.setMaxListeners() to increase limit
(node:32141) UnhandledPromiseRejectionWarning: Error: session store is unavailable
    at Timeout.setTimeout (/home/perfeasy/testingtool/node_modules/koa-generic-session/lib/session.js:441:16)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:32141) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:32141) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

> testingtool-app@1.0.0 start /home/perfeasy/testingtool
> nodemon src/ --exec babel-node

[33m[nodemon] 1.18.9[39m
[33m[nodemon] to restart at any time, enter `rs`[39m
[33m[nodemon] watching: *.*[39m
[32m[nodemon] starting `babel-node src/`[39m
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: EBADF: bad file descriptor, read
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testingtool-app@1.0.0 start: `nodemon src/ --exec babel-node`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the testingtool-app@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/perfeasy/.npm/_logs/2019-01-09T08_34_22_600Z-debug.log
ðŸ–¥  Server started at http://0.0.0.0:4000/
(node:32378) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 job ttl exceeded listeners added. Use emitter.setMaxListeners() to increase limit
here { request: 
   { method: 'POST',
     url: '/app/scenario/save',
     header: 
      { host: '35.185.107.146:4000',
        connection: 'keep-alive',
        'content-length': '113',
        'cache-control': 'max-age=0',
        'request-type': 'ajax',
        origin: 'http://35.185.107.146:4000',
        'user-agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
        'content-type': 'application/json',
        accept: '*/*',
        referer: 'http://35.185.107.146:4000/app/project/5c35b3333d757b7e7acee34e/scenarios',
        'accept-encoding': 'gzip, deflate',
        'accept-language': 'en-US,en;q=0.9',
        cookie: 'IWEB=bILK4BQnNzVnHuDBepKMeznCJDY2J1AU; IWEB.sig=7T73s6L6WVcZfM8v5KJrz-E5IKU' } },
  response: { status: 404, message: 'Not Found', header: {} },
  app: { subdomainOffset: 2, proxy: false, env: 'development' },
  originalUrl: '/app/scenario/save',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>' }
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'uploads/upload_0977c31ef130b231e43f91c5a2c902a4'
